-- ============================================================
--  Migration: iptv_apps table
--  Run this in your MySQL database (cms_db)
-- ============================================================

CREATE TABLE IF NOT EXISTS `iptv_apps` (
  `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(120) NOT NULL,
  `icon`         VARCHAR(10)  NOT NULL DEFAULT '📺',
  `category`     VARCHAR(60)  NOT NULL COMMENT 'smartphone | tv | pc | box',
  `is_free`      TINYINT(1)   NOT NULL DEFAULT 1,
  `price`        JSON         NULL     COMMENT '{"fr":"...","en":"...","es":"...","de":"..."}',
  `platforms`    JSON         NOT NULL COMMENT '["iOS","Android",...]',
  `device_types` JSON         NOT NULL COMMENT '["smartphone","tv","pc","box"]',
  `blog_slug`    VARCHAR(200) NULL,
  `descriptions` JSON         NOT NULL COMMENT '{"fr":"...","en":"...","es":"...","de":"..."}',
  `steps`        JSON         NOT NULL COMMENT '{"fr":["..."],"en":["..."],"es":["..."],"de":["..."]}',
  `status`       ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `sort_order`   SMALLINT     NOT NULL DEFAULT 0,
  `created_at`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_category` (`category`),
  INDEX `idx_status`   (`status`),
  INDEX `idx_sort`     (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
--  Seed data – 25 apps
-- ============================================================

INSERT INTO `iptv_apps`
  (`name`,`icon`,`category`,`is_free`,`price`,`platforms`,`device_types`,`blog_slug`,`descriptions`,`steps`,`status`,`sort_order`)
VALUES

-- ─────────────── SMARTPHONES ────────────────────────────────
('GSE Smart IPTV','📱','smartphone',1,NULL,
 '["iOS","Android"]','["smartphone"]',
 'gse-smart-iptv-guide-complet',
 '{"fr":"L\'application mobile la plus populaire et complète avec support M3U et Xtream Codes.","en":"The most popular and comprehensive mobile app with M3U and Xtream Codes support.","es":"La aplicación móvil más popular y completa con soporte para M3U y Xtream Codes.","de":"Die beliebteste und umfassendste mobile App mit Unterstützung für M3U und Xtream Codes."}',
 '{"fr":["Téléchargez GSE Smart IPTV depuis l\'App Store ou Google Play Store.","Ouvrez le menu latéral gauche et cliquez sur \'Playlists distantes\'.","Cliquez sur le bouton \'+\' puis sur \'Ajouter URL M3U\'.","Entrez l\'URL M3U de votre abonnement RegardezIPTV et validez."],"en":["Download GSE Smart IPTV from the App Store or Play Store.","Open the left sidebar menu and click on \'Remote Playlists\'.","Click the \'+\' button and then \'Add M3U URL\'.","Enter your RegardezIPTV M3U URL and save."],"es":["Descargue GSE Smart IPTV desde la App Store o Play Store.","Abra el menú lateral izquierdo y haga clic en \'Listas de reproducción remotas\'.","Haga clic en el botón \'+\' y luego en \'Añadir URL M3U\'.","Introduzca la URL M3U de su suscripción de RegardezIPTV y guarde."],"de":["Laden Sie GSE Smart IPTV aus dem App Store oder Play Store herunter.","Öffnen Sie das linke Seitenmenü und klicken Sie auf \'Remote-Playlists\'.","Klicken Sie auf das \'+\'-Symbol und wählen Sie \'M3U-URL hinzufügen\'.","Geben Sie die M3U-URL Ihres RegardezIPTV-Abonnements ein und speichern Sie."]}',
 'active',1),

('IPTV Smarters Pro','⚡','smartphone',0,
 '{"fr":"Gratuit / Pro à 3,49€","en":"Free / Pro for €3.49","es":"Gratis / Pro por 3,49€","de":"Kostenlos / Pro für 3,49€"}',
 '["iOS","Android","Fire Stick"]','["smartphone","box"]',NULL,
 '{"fr":"Interface moderne avec gestion multi-playlists, guide des programmes (EPG) et VOD intégrée.","en":"Modern interface with multi-playlist management, TV Guide (EPG), and built-in VOD.","es":"Interfaz moderna con gestión de listas múltiples, guía de programación (EPG) y VOD integrado.","de":"Moderne Benutzeroberfläche mit Multi-Playlist-Verwaltung, EPG und integriertem VOD."}',
 '{"fr":["Installez l\'application depuis votre magasin d\'applications (ou Smarters Player Lite sur iOS).","Choisissez l\'option de connexion \'Xtream Codes API\'.","Entrez le nom de la playlist (ex: RegardezIPTV).","Saisissez votre nom d\'utilisateur, mot de passe et l\'URL du serveur reçus par email.","Cliquez sur \'Add User\' pour charger les chaînes."],"en":["Install the app from your official app store (or Smarters Player Lite on iOS).","Select the login option \'Xtream Codes API\'.","Enter a name for the playlist (e.g., RegardezIPTV).","Enter your username, password, and server URL received by email.","Click \'Add User\' to load the channels."],"es":["Instale la aplicación desde la tienda oficial (o Smarters Player Lite en iOS).","Seleccione la opción de inicio de sesión \'Xtream Codes API\'.","Introduzca un nombre para la lista (ej: RegardezIPTV).","Introduzca su usuario, contraseña y URL del servidor recibidos por email.","Haga clic en \'Add User\' para cargar los canales."],"de":["Installieren Sie die App aus Ihrem App Store (oder Smarters Player Lite unter iOS).","Wählen Sie die Anmeldeoption \'Xtream Codes API\'.","Geben Sie einen Namen für die Playlist ein (z. B. RegardezIPTV).","Geben Sie Ihren Benutzernamen, Ihr Passwort und die Server-URL aus Ihrer E-Mail ein.","Klicken Sie auf \'Add User\', um die Kanäle zu laden."]}',
 'active',2),

('Televizo','📱','smartphone',0,
 '{"fr":"Gratuit / Premium à 2,49€","en":"Free / Premium for €2.49","es":"Gratis / Premium por 2,49€","de":"Kostenlos / Premium für 2,49€"}',
 '["Android TV","Fire Stick","Android"]','["smartphone","box"]',NULL,
 '{"fr":"Lecteur moderne très propre, avec sous-titres, audio multi-pistes, EPG et zapping réactif.","en":"Very clean modern player with subtitles, multi-track audio, EPG, and responsive channel switching.","es":"Reproductor moderno muy limpio, con subtítulos, audio multipista, EPG y cambio rápido de canales.","de":"Sehr sauberer, moderner Player mit Untertiteln, Multi-Audio-Tracks, EPG und schnellem Umschalten."}',
 '{"fr":["Téléchargez Televizo depuis le Google Play Store ou Downloader.","Ouvrez l\'application et cliquez sur \'Ajouter une playlist\'.","Sélectionnez \'Playlist M3U\' ou \'Xtream Codes\'.","Renseignez vos coordonnées IPTV et sauvegardez pour charger."],"en":["Download Televizo from the Google Play Store or via Downloader.","Open the app and click on \'Add playlist\'.","Select \'M3U Playlist\' or \'Xtream Codes\'.","Enter your IPTV details and click save to load the channels."],"es":["Descargue Televizo desde Google Play Store o mediante Downloader.","Abra la aplicación y haga clic en \'Añadir lista\'.","Seleccione \'Lista M3U\' o \'Xtream Codes\'.","Introduzca sus datos de IPTV y pulse guardar para cargar."],"de":["Laden Sie Televizo aus dem Google Play Store oder über Downloader herunter.","Öffnen Sie die App und klicken Sie auf \'Playlist hinzufügen\'.","Wählen Sie \'M3U-Playlist\' oder \'Xtream Codes\'.","Geben Sie Ihre IPTV-Daten ein und speichern Sie."]}',
 'active',3),

-- ─────────────── TV ─────────────────────────────────────────
('Tivimate','📺','tv',0,
 '{"fr":"Payant (4,99€/an)","en":"Paid (€4.99/year)","es":"De pago (4,99€/año)","de":"Kostenpflichtig (4,99€/Jahr)"}',
 '["Android","Android TV","Fire Stick"]','["smartphone","tv","box"]',
 'tivimate-iptv-player-firestick-android-tv',
 '{"fr":"La meilleure application pour Android TV et Fire Stick, offrant une interface similaire à un décodeur traditionnel.","en":"The ultimate application for Android TV and Fire Stick, offering a traditional TV decoder experience.","es":"La mejor aplicación para Android TV y Fire Stick, con una interfaz similar a la de un decodificador tradicional.","de":"Die beste Anwendung für Android TV und Fire Stick mit einer Benutzeroberfläche wie bei einem klassischen Receiver."}',
 '{"fr":["Installez Tivimate sur votre box ou TV Android via le Google Play Store ou Downloader.","Ouvrez l\'application et cliquez sur \'Ajouter une playlist\'.","Sélectionnez \'Xtream Codes\' ou \'Playlist M3U\'.","Entrez vos accès RegardezIPTV reçus par email.","Validez pour charger le guide des programmes (EPG) et les chaînes."],"en":["Install Tivimate on your Android Box or TV via the Play Store or Downloader.","Open the app and click on \'Add playlist\'.","Select \'Xtream Codes\' or \'M3U Playlist\'.","Enter your RegardezIPTV credentials from the email.","Confirm to load the TV guide (EPG) and channels."],"es":["Instale Tivimate en su Android Box o TV a través de Play Store o Downloader.","Abra la aplicación y haga clic en \'Añadir lista\'.","Seleccione \'Xtream Codes\' o \'Lista M3U\'.","Introduzca sus credenciales de RegardezIPTV recibidas por email.","Confirme para cargar la guía de programación (EPG) y los canales."],"de":["Installieren Sie Tivimate auf Ihrer Android Box/TV über den Play Store oder Downloader.","Öffnen Sie die App und klicken Sie auf \'Playlist hinzufügen\'.","Wählen Sie \'Xtream Codes\' oder \'M3U-Playlist\'.","Geben Sie Ihre RegardezIPTV-Zugangsdaten aus der E-Mail ein.","Bestätigen Sie, um den EPG und die Kanäle zu laden."]}',
 'active',4),

('Smart IPTV (SIPTV)','🖥️','tv',0,
 '{"fr":"Payant (5,49€ une fois)","en":"Paid (€5.49 one-time)","es":"De pago (5,49€ pago único)","de":"Kostenpflichtig (5,49€ einmalig)"}',
 '["Samsung","LG","Android TV"]','["tv"]',NULL,
 '{"fr":"L\'application historique de référence pour Smart TV Samsung et LG, légère et performante.","en":"The historical benchmark app for Samsung and LG Smart TVs, lightweight and highly optimized.","es":"La aplicación de referencia histórica para Smart TV Samsung y LG, ligera y de alto rendimiento.","de":"Der historische Klassiker für Samsung und LG Smart TVs, extrem leicht und performant."}',
 '{"fr":["Installez Smart IPTV (SIPTV) depuis le store d\'applications de votre TV Samsung ou LG.","Notez l\'adresse MAC affichée à l\'écran (ex: ab:cd:ef:12:34:56).","Sur PC ou mobile, rendez-vous sur le site siptv.app/mylist/.","Saisissez l\'adresse MAC, collez l\'URL M3U de votre abonnement et cliquez sur \'Send\'."],"en":["Install Smart IPTV (SIPTV) from your TV\'s app store.","Note down the MAC address shown on screen (e.g., ab:cd:ef:12:34:56).","On a PC or mobile, go to the website siptv.app/mylist/.","Enter your MAC address, paste your M3U URL, and click \'Send\'."],"es":["Instale Smart IPTV (SIPTV) desde la tienda de aplicaciones de su televisor.","Anote la dirección MAC que aparece en pantalla (ej: ab:cd:ef:12:34:56).","Desde un PC o móvil, vaya al sitio web siptv.app/mylist/.","Introduzca su dirección MAC, pegue la URL M3U de su suscripción y pulse \'Send\'."],"de":["Installieren Sie Smart IPTV (SIPTV) aus dem App-Store Ihres Fernsehers.","Notieren Sie sich die angezeigte MAC-Adresse (z. B. ab:cd:ef:12:34:56).","Gehen Sie am PC oder Smartphone auf die Website siptv.app/mylist/.","Geben Sie die MAC-Adresse ein, fügen Sie Ihre M3U-URL ein und klicken Sie auf \'Send\'."]}',
 'active',5),

('SS IPTV','🌐','tv',1,NULL,
 '["Samsung","LG","Android TV"]','["tv"]',
 'configurer-code-iptv-ss-iptv',
 '{"fr":"Application entièrement gratuite pour TV connectées supportant le zapping direct et le chargement à distance.","en":"Completely free application for connected Smart TVs supporting instant zapping and remote playlist loading.","es":"Aplicación totalmente gratuita para Smart TV con soporte para cambio rápido de canal y carga remota de listas.","de":"Völlig kostenlose App für Smart TVs mit Unterstützung für schnelles Zappen und Remote-Playlists."}',
 '{"fr":["Recherchez et installez SS IPTV sur le Content Store LG ou Samsung App Store.","Ouvrez l\'application, allez dans Paramètres (engrenage), et cliquez sur \'Obtenir le code de connexion\'.","Rendez-vous sur le site officiel ss-iptv.com dans la section éditeur de playlist.","Entrez le code pour lier votre TV, ajoutez une playlist externe et insérez votre URL M3U."],"en":["Search and install SS IPTV from the LG Content Store or Samsung App Store.","Open the app, go to Settings, and click \'Get connection code\'.","Visit the official website ss-iptv.com and go to the playlist editor section.","Enter the code to link your TV, add an external playlist, and paste your M3U URL."],"es":["Busque e instale SS IPTV en LG Content Store o Samsung App Store.","Abra la aplicación, vaya a Ajustes y haga clic en \'Obtener código de conexión\'.","Vaya al sitio web oficial ss-iptv.com en la sección de editor de listas.","Introduzca el código para vincular su TV, añada una lista externa e inserte su URL M3U."],"de":["Suchen und installieren Sie SS IPTV auf Ihrem LG oder Samsung Smart TV.","Öffnen Sie die App, gehen Sie in die Einstellungen und klicken Sie auf \'Verbindungscode abrufen\'.","Besuchen Sie die offizielle Website ss-iptv.com im Bereich Playlist-Editor.","Geben Sie den Code ein, um Ihren TV zu koppeln, fügen Sie eine externe Playlist hinzu und tragen Sie Ihre M3U-URL ein."]}',
 'active',6),

('Net IPTV','🌐','tv',0,
 '{"fr":"Payant (5,79€ à vie)","en":"Paid (€5.79 lifetime)","es":"De pago (5,79€ de por vida)","de":"Kostenpflichtig (5,79€ lebenslang)"}',
 '["Samsung","LG","Android TV"]','["tv"]',NULL,
 '{"fr":"Alternative moderne à Smart IPTV avec chargement rapide et excellente stabilité d\'image.","en":"Modern alternative to Smart IPTV featuring fast loading times and excellent stream stability.","es":"Alternativa moderna a Smart IPTV con carga rápida y una excelente estabilidad de imagen.","de":"Moderne Alternative zu Smart IPTV mit schnellen Ladezeiten und hervorragender Stabilität."}',
 '{"fr":["Installez Net IPTV sur votre Smart TV.","Notez l\'adresse MAC de votre appareil affichée au lancement.","Allez sur le site netiptv.eu/upload.","Saisissez l\'adresse MAC, résolvez le captcha, puis collez l\'URL M3U dans le champ \'List 1\' et validez."],"en":["Install Net IPTV on your Smart TV.","Note down the MAC address displayed at launch.","Visit the website netiptv.eu/upload.","Enter the MAC address, solve the captcha, paste your M3U URL under \'List 1\', and submit."],"es":["Instale Net IPTV en su Smart TV.","Anote la dirección MAC de su dispositivo que aparece al iniciar.","Vaya al sitio web netiptv.eu/upload.","Introduzca la dirección MAC, resuelva el captcha, pegue la URL M3U en el campo \'List 1\' y confirme."],"de":["Installieren Sie Net IPTV auf Ihrem Smart TV.","Notieren Sie sich die beim Start angezeigte MAC-Adresse.","Gehen Sie auf die Website netiptv.eu/upload.","Geben Sie die MAC-Adresse ein, lösen Sie das Captcha, fügen Sie Ihre M3U-URL unter \'List 1\' ein und bestätigen Sie."]}',
 'active',7),

('IBO Player','💎','tv',0,
 '{"fr":"Payant (8,00€/an)","en":"Paid (€8.00/year)","es":"De pago (8,00€/año)","de":"Kostenpflichtig (8,00€/Jahr)"}',
 '["Samsung","LG","Android TV","Fire Stick"]','["tv","box"]',NULL,
 '{"fr":"Un lecteur haut de gamme avec une interface fluide, gérant les groupes de chaînes et VOD 4K sans saccades.","en":"A premium player with a fluid UI, managing channel groups and 4K VOD without stutter.","es":"Un reproductor premium con una interfaz fluida, que gestiona grupos de canales y VOD 4K sin cortes.","de":"Ein Premium-Player mit einer sehr flüssigen UI, der Kanalgruppen und 4K-VOD ruckelfrei abspielt."}',
 '{"fr":["Téléchargez IBO Player sur votre Smart TV ou appareil Android.","Notez le \'Device ID\' et \'Device Key\' affichés à l\'écran.","Allez sur le portail iboplayer.com.","Connectez-vous avec vos identifiants d\'appareil, ajoutez votre playlist M3U et redémarrez l\'application."],"en":["Download IBO Player on your Smart TV or Android device.","Note down the \'Device ID\' and \'Device Key\' shown on screen.","Go to the portal at iboplayer.com.","Log in with your device credentials, add your M3U playlist, and restart the app on your TV."],"es":["Descargue IBO Player en su Smart TV o dispositivo Android.","Anote el \'Device ID\' y \'Device Key\' que aparecen en pantalla.","Vaya al portal en iboplayer.com.","Inicie sesión con las credenciales de su dispositivo, añada su lista M3U y reinicie la aplicación en su TV."],"de":["Laden Sie IBO Player auf Ihren Smart TV oder Ihr Android-Gerät herunter.","Notieren Sie sich die auf dem Bildschirm angezeigte \'Device ID\' und \'Device Key\'.","Gehen Sie auf das Webportal iboplayer.com.","Melden Sie sich mit den Gerätedaten an, fügen Sie Ihre M3U-Playlist hinzu und starten Sie die App neu."]}',
 'active',8),

('Duplex IPTV','📽️','tv',0,
 '{"fr":"Payant (1,99€/an)","en":"Paid (€1.99/year)","es":"De pago (1,99€/año)","de":"Kostenpflichtig (1,99€/Jahr)"}',
 '["Samsung","LG","Android TV"]','["tv"]',NULL,
 '{"fr":"Interface épurée et très intuitive, supportant les flux 4K, l\'EPG XMLTV et les pistes audio multiples.","en":"Sleek and highly intuitive UI supporting 4K streams, XMLTV EPG, and multiple audio tracks.","es":"Interfaz elegante y muy intuitiva, compatible con flujos 4K, EPG XMLTV y múltiples pistas de audio.","de":"Sehr übersichtliche und intuitive UI mit Unterstützung für 4K-Streams, XMLTV-EPG und mehrere Tonspuren."}',
 '{"fr":["Installez DuplexPlay (Duplex IPTV) sur votre téléviseur.","Notez l\'ID de l\'appareil (Device ID) et l\'adresse MAC (Device MAC) affichés.","Visitez edit.duplexplay.com depuis un navigateur.","Entrez vos codes d\'appareil, puis cliquez sur \'Add Playlist\' et collez l\'URL M3U de votre abonnement."],"en":["Install DuplexPlay on your TV.","Note down the Device ID and Device MAC shown on screen.","Visit edit.duplexplay.com from any browser.","Enter your device credentials, click \'Add Playlist\', and paste your subscription M3U URL."],"es":["Instale DuplexPlay en su televisor.","Anote el Device ID y Device MAC que se muestran en pantalla.","Visite edit.duplexplay.com desde cualquier navegador.","Introduzca sus códigos de dispositivo, haga clic en \'Add Playlist\' y pegue la URL M3U de su suscripción."],"de":["Installieren Sie DuplexPlay auf Ihrem Fernseher.","Notieren Sie sich die angezeigte Device ID und Device MAC.","Besuchen Sie edit.duplexplay.com in einem Browser.","Geben Sie Ihre Gerätedaten ein, klicken Sie auf \'Add Playlist\' und fügen Sie Ihre M3U-URL hinzu."]}',
 'active',9),

('Flix IPTV','🎬','tv',0,
 '{"fr":"Payant (7,49€ une fois)","en":"Paid (€7.49 one-time)","es":"De pago (7,49€ pago único)","de":"Kostenpflichtig (7,49€ einmalig)"}',
 '["Samsung","LG","Android TV","Fire Stick"]','["tv","box"]',
 'installer-flix-iptv-guide-etape-par-etape',
 '{"fr":"Lecteur moderne de haute qualité avec zapping instantané et sous-titres personnalisables.","en":"Modern, high-quality player with instant channel switching and customizable subtitles.","es":"Reproductor moderno de alta calidad con cambio instantáneo de canal y subtítulos personalizables.","de":"Moderner, hochwertiger Player mit schnellem Umschalten und anpassbaren Untertiteln."}',
 '{"fr":["Installez Flix IPTV depuis le magasin d\'applications de votre Smart TV.","Notez l\'adresse MAC affichée sur l\'écran d\'accueil.","Rendez-vous sur le site flixiptv.eu/mylist.","Entrez votre adresse MAC et votre lien M3U de RegardezIPTV, puis cliquez sur envoyer."],"en":["Install Flix IPTV from your Smart TV\'s app store.","Note down the MAC address displayed on the home screen.","Visit the website flixiptv.eu/mylist.","Enter your MAC address and your RegardezIPTV M3U link, and submit."],"es":["Instale Flix IPTV desde la tienda de aplicaciones de su Smart TV.","Anote la dirección MAC que aparece en la pantalla de inicio.","Vaya al sitio web flixiptv.eu/mylist.","Introduzca su dirección MAC y su enlace M3U de RegardezIPTV, y haga clic en enviar."],"de":["Installieren Sie Flix IPTV aus dem App-Store Ihres Fernsehers.","Notieren Sie sich die beim Start angezeigte MAC-Adresse.","Besuchen Sie die Website flixiptv.eu/mylist.","Geben Sie Ihre MAC-Adresse und Ihre RegardezIPTV M3U-URL ein und senden Sie sie ab."]}',
 'active',10),

('Smart One IPTV','☝️','tv',0,
 '{"fr":"Payant (2,50€/an)","en":"Paid (€2.50/year)","es":"De pago (2,50€/año)","de":"Kostenpflichtig (2,50€/Jahr)"}',
 '["Samsung","LG","Android TV","Fire Stick"]','["tv","box"]',
 'smart-one-iptv-smart-tv-samsung-lg',
 '{"fr":"Une application complète et performante avec support multi-playlists et gestion du replay.","en":"A comprehensive and high-performance app with multi-playlist and catch-up TV support.","es":"Una aplicación completa y potente con soporte para múltiples listas y gestión de diferidos.","de":"Eine leistungsstarke und umfassende App mit Unterstützung für Multi-Playlists und Replay."}',
 '{"fr":["Installez Smart One IPTV sur votre TV connectée Samsung ou LG.","Récupérez le \'Mac Address\' et \'Key\' affichés à l\'écran.","Allez sur le site smartone-iptv.com/plugin/class_api.","Entrez vos codes de connexion et collez l\'URL M3U de votre abonnement, puis sauvegardez."],"en":["Install Smart One IPTV on your Smart TV.","Get the MAC Address and Key displayed on the screen.","Visit the website smartone-iptv.com/plugin/class_api.","Enter your connection codes, paste your subscription M3U URL, and save."],"es":["Instale Smart One IPTV en su Smart TV.","Obtenga la dirección MAC y la clave que aparecen en pantalla.","Vaya al sitio web smartone-iptv.com/plugin/class_api.","Introduzca sus códigos de conexión, pegue la URL M3U de su suscripción y guarde."],"de":["Installieren Sie Smart One IPTV auf Ihrem Smart TV.","Notieren Sie sich die angezeigte MAC-Adresse und den Key.","Gehen Sie auf die Website smartone-iptv.com/plugin/class_api.","Geben Sie Ihre Daten ein, fügen Sie Ihre M3U-URL hinzu und speichern Sie."]}',
 'active',11),

('SET IPTV','🖥️','tv',0,
 '{"fr":"Payant (14,99€ à vie)","en":"Paid (€14.99 lifetime)","es":"De pago (14,99€ de por vida)","de":"Kostenpflichtig (14,99€ lebenslang)"}',
 '["Samsung","LG","Android TV","Fire Stick"]','["tv","box"]',NULL,
 '{"fr":"Un lecteur épuré et moderne, optimisé pour les Smart TV Samsung de dernière génération.","en":"A clean and modern player, optimized for the latest generation of Samsung Smart TVs.","es":"Un reproductor elegante y moderno, optimizado para los Smart TV Samsung de última generación.","de":"Ein sehr moderner und minimalistischer Player, optimiert für Samsung Smart TVs der neuesten Generation."}',
 '{"fr":["Installez l\'application SET IPTV depuis le store de votre appareil.","Notez l\'adresse MAC affichée à l\'écran de l\'application.","Allez sur le portail d\'activation setiptv.net/set.php.","Saisissez l\'adresse MAC, collez le lien M3U reçu de RegardezIPTV et validez."],"en":["Install the SET IPTV app from your device\'s app store.","Note down the MAC address displayed on the screen.","Visit the activation portal at setiptv.net/set.php.","Enter your MAC address, paste the RegardezIPTV M3U link, and submit."],"es":["Instale la aplicación SET IPTV desde la tienda de su dispositivo.","Anote la dirección MAC que aparece en la pantalla.","Vaya al portal de activación setiptv.net/set.php.","Introduzca la dirección MAC, pegue el enlace M3U de RegardezIPTV y confirme."],"de":["Installieren Sie SET IPTV aus dem App-Store Ihres Geräts.","Notieren Sie sich die angezeigte MAC-Adresse.","Gehen Sie auf das Aktivierungsportal setiptv.net/set.php.","Tragen Sie die MAC-Adresse ein, fügen Sie Ihre RegardezIPTV M3U-URL hinzu und bestätigen Sie."]}',
 'active',12),

('Royal IPTV','👑','tv',0,
 '{"fr":"Payant (5,49€ à vie)","en":"Paid (€5.49 lifetime)","es":"De pago (5,49€ de por vida)","de":"Kostenpflichtig (5,49€ lebenslang)"}',
 '["Samsung","LG"]','["tv"]',NULL,
 '{"fr":"Lecteur simple et de haute qualité avec un chargement rapide de l\'EPG et une interface épurée.","en":"Simple and high-quality player with quick EPG loading and a clean, uncluttered user interface.","es":"Reproductor simple y de alta calidad con carga rápida de la EPG y una interfaz limpia.","de":"Einfacher und hochwertiger Player mit schnellem EPG-Ladevorgang und übersichtlicher Benutzeroberfläche."}',
 '{"fr":["Installez Royal IPTV sur votre TV connectée Samsung ou LG.","Notez la MAC adresse affichée.","Visitez le site web officiel de Royal IPTV (royaliptvapp.com).","Allez dans la section d\'upload, entrez la MAC et liez votre URL M3U de RegardezIPTV."],"en":["Install Royal IPTV on your Samsung or LG Smart TV.","Note down the displayed MAC address.","Visit the official Royal IPTV website (royaliptvapp.com).","Go to the upload section, enter the MAC, and link your RegardezIPTV M3U URL."],"es":["Instale Royal IPTV en su Smart TV Samsung o LG.","Anote la dirección MAC mostrada.","Visite el sitio web oficial de Royal IPTV (royaliptvapp.com).","Vaya a la sección de carga, introduzca la MAC y vincule su URL M3U de RegardezIPTV."],"de":["Installieren Sie Royal IPTV auf Ihrem Samsung oder LG Smart TV.","Notieren Sie sich die angezeigte MAC-Adresse.","Besuchen Sie die offizielle Website (royaliptvapp.com).","Gehen Sie zum Upload-Bereich, tragen Sie die MAC-Adresse ein und verknüpfen Sie Ihre RegardezIPTV M3U-URL."]}',
 'active',13),

('Nano IPTV','🧬','tv',0,
 '{"fr":"Payant (4,99€ une fois)","en":"Paid (€4.99 one-time)","es":"De pago (4,99€ un pago único)","de":"Kostenpflichtig (4,99€ einmalig)"}',
 '["Samsung","LG"]','["tv"]',NULL,
 '{"fr":"Une application minimaliste axée sur la rapidité de navigation et le support des playlists géantes.","en":"A minimalist application focused on navigation speed and support for huge playlists.","es":"Una aplicación minimalista centrada en la rapidez de navegación y el soporte para listas gigantes.","de":"Eine minimalistische App mit Fokus auf Navigationsgeschwindigkeit und Unterstützung für riesige Playlists."}',
 '{"fr":["Téléchargez Nano IPTV sur votre TV connectée Samsung ou LG.","Récupérez l\'adresse MAC affichée à l\'écran.","Allez sur nano-iptv.com/upload.","Renseignez votre MAC et collez l\'URL M3U pour activer votre playlist."],"en":["Download Nano IPTV on your Smart TV.","Retrieve the MAC address shown on screen.","Visit nano-iptv.com/upload.","Enter your MAC and paste the M3U URL to activate your playlist."],"es":["Descargue Nano IPTV en su Smart TV.","Obtenga la dirección MAC que aparece en pantalla.","Vaya a nano-iptv.com/upload.","Introduzca su MAC y pegue la URL M3U para activar su lista."],"de":["Laden Sie Nano IPTV auf Ihren Smart TV herunter.","Notieren Sie sich die angezeigte MAC-Adresse.","Gehen Sie auf nano-iptv.com/upload.","Tragen Sie die MAC-Adresse ein und fügen Sie Ihre M3U-URL hinzu."]}',
 'active',14),

-- ─────────────── PC ──────────────────────────────────────────
('VLC Media Player','🔶','pc',1,NULL,
 '["Windows","Mac","Linux"]','["pc"]',NULL,
 '{"fr":"Le lecteur média universel open-source, parfait pour tester ou regarder l\'IPTV sur ordinateur.","en":"The universal open-source media player, perfect for testing or watching IPTV on computers.","es":"El reproductor de medios universal de código abierto, perfecto para probar o ver IPTV en el ordenador.","de":"Der universelle Open-Source-Mediaplayer, perfekt zum Testen oder Anschauen von IPTV auf dem PC."}',
 '{"fr":["Téléchargez et installez VLC Media Player depuis le site officiel de VideoLAN.","Ouvrez VLC, allez dans Média > Ouvrir un flux réseau (Ctrl+N).","Collez l\'URL M3U de votre abonnement dans le champ d\'adresse.","Cliquez sur \'Lire\'. Affichez la liste de lecture (Ctrl+L) pour naviguer entre les chaînes."],"en":["Download and install VLC Media Player from the official VideoLAN website.","Open VLC, navigate to Media > Open Network Stream (Ctrl+N).","Paste your subscription M3U URL into the address field.","Click \'Play\'. Toggle the playlist view (Ctrl+L) to navigate through channels."],"es":["Descargue e instale VLC Media Player desde el sitio web oficial de VideoLAN.","Abra VLC, vaya a Medio > Abrir volcado de red (Ctrl+N).","Pegue la URL M3U de su suscripción en el campo de dirección.","Haga clic en \'Reproducir\'. Active la lista de reproducción (Ctrl+L) para navegar por los canales."],"de":["Laden Sie VLC Media Player von der offiziellen VideoLAN-Website herunter und installieren Sie ihn.","Öffnen VLC, gehen Sie auf Medien > Netzwerkstream öffnen (Strg+N).","Fügen Sie Ihre M3U-URL in das Adressfeld ein.","Klicken Sie auf \'Wiedergabe\'. Drücken Sie Strg+L, um die Playlist anzuzeigen und Kanäle auszuwählen."]}',
 'active',15),

('MyIPTV Player','💻','pc',1,NULL,
 '["Windows"]','["pc"]',NULL,
 '{"fr":"Application Windows native disponible sur le Microsoft Store, avec un bon support EPG et filtres.","en":"Native Windows application available on the Microsoft Store, featuring solid EPG support and channel filters.","es":"Aplicación nativa de Windows disponible en Microsoft Store, con buen soporte de EPG y filtros de canales.","de":"Native Windows-App aus dem Microsoft Store mit gutem EPG-Support und Kanalsortierung."}',
 '{"fr":["Installez MyIPTV Player depuis le Microsoft Store de Windows 10/11.","Allez dans Settings > Add new playlist and EPG source.","Collez votre URL M3U de RegardezIPTV dans la section \'Remote channel list\'.","Nommez-la, cliquez sur \'Add list\', puis sélectionnez-la dans la page des paramètres généraux et cliquez sur \'Refresh\'."],"en":["Install MyIPTV Player from the Microsoft Store on Windows 10/11.","Go to Settings > Add new playlist and EPG source.","Paste your RegardezIPTV M3U URL under the \'Remote channel list\' section.","Name the list, click \'Add list\', go back to general settings, select it, and click \'Refresh\'."],"es":["Instale MyIPTV Player desde Microsoft Store en Windows 10/11.","Vaya a Ajustes > Añadir nueva lista y fuente EPG.","Pegue su URL M3U de RegardezIPTV en la sección \'Remote channel list\'.","Asigne un nombre, haga clic en \'Add list\', regrese a ajustes generales, selecciónela y haga clic en \'Refresh\'."],"de":["Installieren Sie MyIPTV Player aus dem Microsoft Store unter Windows 10/11.","Gehen Sie zu Einstellungen > Neue Playlist und EPG-Quelle hinzufügen.","Fügen Sie Ihre RegardezIPTV M3U-URL unter \'Remote-Kanalliste\' ein.","Geben Sie einen Namen ein, klicken Sie auf \'Add list\', wählen Sie sie in den Haupteinstellungen aus und klicken Sie auf \'Refresh\'."]}',
 'active',16),

('IPTVnator','🗺️','pc',1,NULL,
 '["Windows","Mac","Linux"]','["pc"]',NULL,
 '{"fr":"Lecteur IPTV open-source moderne basé sur Electron, compatible avec tous les systèmes d\'exploitation PC.","en":"Modern open-source IPTV player based on Electron, compatible with all desktop operating systems.","es":"Reproductor IPTV moderno de código abierto basado en Electron, compatible con todos los sistemas operativos de PC.","de":"Moderner Open-Source-IPTV-Player auf Electron-Basis, kompatibel mit allen Desktop-Betriebssystemen."}',
 '{"fr":["Téléchargez la dernière version d\'IPTVnator sur GitHub.","Lancez l\'application et cliquez sur \'Add Playlist\'.","Sélectionnez \'Via URL\' et collez votre lien M3U de RegardezIPTV.","Validez pour importer vos bouquets de chaînes et VOD."],"en":["Download the latest version of IPTVnator from GitHub.","Launch the app and click on \'Add Playlist\'.","Select \'Via URL\' and paste your RegardezIPTV M3U link.","Confirm to import your channel groups and VOD."],"es":["Descargue la última versión de IPTVnator desde GitHub.","Inicie la aplicación y haga clic en \'Add Playlist\'.","Seleccione \'Via URL\' y pegue su enlace M3U de RegardezIPTV.","Confirme para importar sus grupos de canales y VOD."],"de":["Laden Sie die neueste Version von IPTVnator von GitHub herunter.","Starten Sie die App und klicken Sie auf \'Playlist hinzufügen\'.","Wählen Sie \'Via URL\' und fügen Sie Ihre RegardezIPTV M3U-URL ein.","Bestätigen Sie, um Ihre Kanäle und VOD-Inhalte zu laden."]}',
 'active',17),

('ProgTV','📡','pc',0,
 '{"fr":"Gratuit / Pro à 9,99€","en":"Free / Pro for €9.99","es":"Gratis / Pro por 9,99€","de":"Kostenlos / Pro für 9,99€"}',
 '["Windows","Android"]','["smartphone","pc"]',NULL,
 '{"fr":"Lecteur classique et très puissant doté d\'options de personnalisation avancées pour les flux TV en direct.","en":"Classic and highly powerful player featuring advanced customization options for live TV streams.","es":"Reproductor clásico y muy potente con opciones de personalización avanzadas para flujos de TV en directo.","de":"Klassischer und sehr leistungsstarker Player mit erweiterten Anpassungsoptionen für Live-TV-Streams."}',
 '{"fr":["Téléchargez ProgTV depuis le site officiel progdvb.com.","Ouvrez l\'application, allez dans Sources > Liste de lecture M3U.","Saisissez l\'URL de votre abonnement RegardezIPTV dans l\'adresse de la playlist.","Cliquez sur valider et attendez la fin de la synchronisation des chaînes."],"en":["Download ProgTV from the official website progdvb.com.","Open the app, navigate to Sources > M3U Playlist.","Enter your RegardezIPTV subscription URL in the playlist address field.","Click confirm and wait for the channels to synchronize."],"es":["Descargue ProgTV desde el sitio web oficial progdvb.com.","Abra la aplicación, vaya a Fuentes > Lista de reproducción M3U.","Introduzca la URL de su suscripción de RegardezIPTV en el campo de dirección.","Haga clic en confirmar y espere a que los canales se sincronicen."],"de":["Laden Sie ProgTV von der offiziellen Website progdvb.com herunter.","Öffnen die App und gehen Sie auf Quellen > M3U-Playlist.","Tragen Sie die URL Ihres RegardezIPTV-Abonnements in das Playlist-Feld ein.","Klicken Sie auf Bestätigen und warten Sie, bis die Kanäle geladen sind."]}',
 'active',18),

-- ─────────────── BOX ─────────────────────────────────────────
('XCIPTV','🚀','box',1,NULL,
 '["Android","Android TV","Fire Stick"]','["smartphone","tv","box"]',NULL,
 '{"fr":"Lecteur IPTV simple, léger et ergonomique avec un lecteur vidéo natif très stable.","en":"Simple, lightweight, and user-friendly IPTV player with a highly stable native media player.","es":"Reproductor de IPTV simple, ligero y ergonómico con un reproductor de vídeo nativo muy estable.","de":"Einfacher, leichter und benutzerfreundlicher IPTV-Player mit einem sehr stabilen nativen Videoplayer."}',
 '{"fr":["Téléchargez XCIPTV sur votre appareil Android.","Sur l\'écran d\'accueil, saisissez l\'URL de notre serveur Xtream Codes.","Entrez vos identifiants (nom d\'utilisateur et mot de passe).","Cliquez sur \'Sign In\' pour importer automatiquement les chaînes, EPG et VOD."],"en":["Download XCIPTV on your Android device.","On the home screen, enter our Xtream Codes server URL.","Enter your credentials (username and password).","Click \'Sign In\' to automatically import channels, EPG, and VOD."],"es":["Descargue XCIPTV en su dispositivo Android.","En la pantalla de inicio, introduzca la URL de nuestro servidor Xtream Codes.","Introduzca sus credenciales (usuario y contraseña).","Haga clic en \'Sign In\' para importar automáticamente canales, EPG y VOD."],"de":["Laden Sie XCIPTV auf Ihr Android-Gerät herunter.","Geben Sie auf dem Startbildschirm unsere Xtream-Codes Server-URL ein.","Tragen Sie Ihren Benutzernamen und Ihr Passwort ein.","Klicken Sie auf \'Sign In\', um Kanäle, EPG und VOD zu importieren."]}',
 'active',19),

('OTT Navigator','🧭','box',1,NULL,
 '["Android","Android TV","Fire Stick"]','["smartphone","tv","box"]',NULL,
 '{"fr":"Une application hautement personnalisable avec suivi des épisodes de séries et enregistrement en direct.","en":"A highly customizable application featuring series episode tracking and live recording support.","es":"Una aplicación muy personalizable con seguimiento de episodios de series y grabación en directo.","de":"Eine hochgradig anpassbare App mit Serien-Tracking-Funktion und Live-Aufnahme-Unterstützung."}',
 '{"fr":["Téléchargez l\'application depuis le Google Play Store ou via APK.","Allez dans Paramètres > Fournisseur > Ajouter un fournisseur.","Sélectionnez \'Lien M3U\' ou \'Xtream Codes API\'.","Saisissez les informations de votre abonnement et validez."],"en":["Download the app from the Play Store or via APK.","Go to Settings > Provider > Add provider.","Select \'M3U link\' or \'Xtream Codes API\'.","Enter your subscription details and save."],"es":["Descargue la aplicación desde Play Store o mediante APK.","Vaya a Ajustes > Proveedor > Añadir proveedor.","Seleccione \'Enlace M3U\' o \'Xtream Codes API\'.","Introduzca los datos de su suscripción y guarde."],"de":["Laden Sie die App aus dem Play Store oder als APK herunter.","Gehen Sie zu Einstellungen > Anbieter > Anbieter hinzufügen.","Wählen Sie \'M3U-Link\' oder \'Xtream Codes API\'.","Geben Sie Ihre Abonnementdaten ein und bestätigen Sie."]}',
 'active',20),

('Perfect Player','🎯','box',1,NULL,
 '["Android TV","Fire Stick"]','["box"]',NULL,
 '{"fr":"Un lecteur léger au design épuré, idéal pour les appareils de faible puissance comme les box Android d\'entrée de gamme.","en":"A lightweight player with a clean layout, ideal for lower-spec devices like budget Android boxes.","es":"Un reproductor ligero con un diseño limpio, ideal para dispositivos de gama baja como Android box económicos.","de":"Ein leichter Player mit minimalistischem Layout, ideal für leistungsschwächere Geräte wie günstige Android-Boxen."}',
 '{"fr":["Installez Perfect Player sur votre box Android.","Ouvrez les paramètres (icône engrenage) > Général.","Sélectionnez \'Playlist\' et insérez l\'URL M3U de votre abonnement.","Revenez à l\'écran principal pour charger les flux."],"en":["Install Perfect Player on your Android box.","Open settings (gear icon) > General.","Select \'Playlist\' and enter your subscription M3U URL.","Go back to the main screen to load the streams."],"es":["Instale Perfect Player en su Android box.","Abra la configuración (icono de engranaje) > General.","Seleccione \'Lista de reproducción\' e introduzca su URL M3U.","Vuelva a la pantalla principal para cargar las transmisiones."],"de":["Installieren Sie Perfect Player auf Ihrer Android-Box.","Öffnen Sie die Einstellungen (Zahnrad-Symbol) > Allgemein.","Wählen Sie \'Playlist\' und tragen Sie Ihre M3U-URL ein.","Kehren Sie zum Hauptbildschirm zurück, um die Streams zu laden."]}',
 'active',21),

('IPTV Extreme','🔥','box',0,
 '{"fr":"Gratuit / Pro à 1,19€","en":"Free / Pro for €1.19","es":"Gratis / Pro por 1,19€","de":"Kostenlos / Pro für 1,19€"}',
 '["Android","Android TV","Fire Stick"]','["smartphone","tv","box"]',NULL,
 '{"fr":"Lecteur classique et robuste doté d\'un contrôle parental et d\'une intégration EPG complète.","en":"Classic, robust player featuring parental control options and comprehensive EPG integration.","es":"Reproductor clásico y robusto con control parental e integración completa de EPG.","de":"Klassischer und robuster Player mit Kindersicherung und vollständiger EPG-Integration."}',
 '{"fr":["Installez IPTV Extreme sur votre appareil Android.","Notez l\'adresse MAC affichée à l\'écran de l\'application.","Rendez-vous sur le site officiel de l\'application (iptvextreme.eu).","Renseignez votre adresse MAC et collez l\'URL M3U de RegardezIPTV pour activer."],"en":["Install IPTV Extreme on your Android device.","Note down the MAC Address displayed on the screen.","Visit the official app website (iptvextreme.eu).","Enter your MAC address and paste your RegardezIPTV M3U URL to activate."],"es":["Instale IPTV Extreme en su dispositivo Android.","Anote la dirección MAC que aparece en la pantalla.","Visite el sitio web oficial de la aplicación (iptvextreme.eu).","Introduzca su dirección MAC y pegue la URL M3U de RegardezIPTV para activar."],"de":["Installieren Sie IPTV Extreme auf Ihrem Android-Gerät.","Notieren Sie sich die auf dem Bildschirm angezeigte MAC-Adresse.","Besuchen Sie die offizielle Website (iptvextreme.eu).","Geben Sie Ihre MAC-Adresse ein und fügen Sie Ihre RegardezIPTV M3U-URL hinzu."]}',
 'active',22),

-- ─────────────── MULTI-PLATEFORME ────────────────────────────
('Kodi','📦','smartphone',1,NULL,
 '["Windows","Mac","Linux","Android","iOS"]','["smartphone","tv","pc","box"]',NULL,
 '{"fr":"Centre multimédia open-source ultra-complet, lisant les flux IPTV via l\'extension PVR IPTV Simple Client.","en":"Fully-featured open-source media center that reads IPTV streams via the PVR IPTV Simple Client addon.","es":"Centro multimedia de código abierto súper completo, que lee flujos de IPTV mediante la extensión PVR IPTV Simple Client.","de":"Sehr umfangreiches Open-Source-Mediencenter, das IPTV-Streams über das Add-on PVR IPTV Simple Client wiedergibt."}',
 '{"fr":["Téléchargez et ouvrez Kodi sur votre machine.","Allez dans Extensions > Mes extensions > Clients enregistreurs vidéo.","Sélectionnez \'PVR IPTV Simple Client\' et cliquez sur Installer.","Allez dans Configurer > Général, puis entrez votre URL M3U et validez."],"en":["Download and open Kodi on your device.","Navigate to Add-ons > My Add-ons > PVR Clients.","Select \'PVR IPTV Simple Client\' and install it.","Go to Configure > General, enter your M3U URL, and confirm."],"es":["Descargue y abra Kodi en su dispositivo.","Vaya a Add-ons > Mis add-ons > Clientes PVR.","Seleccione \'PVR IPTV Simple Client\' e instálelo.","Vaya a Configurar > General, introduzca su URL M3U y confirme."],"de":["Laden Sie Kodi herunter und öffnen Sie es auf Ihrem Gerät.","Gehen Sie zu Add-ons > Meine Add-ons > PVR-Clients.","Wählen Sie \'PVR IPTV Simple Client\' und installieren Sie es.","Gehen Sie auf Konfigurieren > Allgemein, tragen Sie Ihre M3U-URL ein und bestätigen Sie."]}',
 'active',23),

('Plex','📽️','pc',1,NULL,
 '["Windows","Mac","Android","iOS","Smart TV"]','["smartphone","tv","pc","box"]',NULL,
 '{"fr":"Principalement un serveur multimédia, Plex permet d\'intégrer des listes IPTV via des plugins tiers ou xTeVe.","en":"Primarily a media server, Plex allows IPTV playlist integration via third-party plugins or xTeVe.","es":"Principalmente un servidor multimedia, Plex permite integrar listas de IPTV mediante plugins de terceros o xTeVe.","de":"Plex ist primär ein Medienserver, ermöglicht jedoch die IPTV-Integration über Drittanbieter-Plugins oder xTeVe."}',
 '{"fr":["Téléchargez Plex Media Server sur votre ordinateur.","Installez un proxy IPTV comme xTeVe pour émuler un tuner HDHomeRun.","Configurez xTeVe avec votre URL M3U et XMLTV de RegardezIPTV.","Dans Plex, allez dans Réglages > Live TV & DVR et ajoutez le tuner local xTeVe."],"en":["Download Plex Media Server on your computer.","Install an IPTV proxy like xTeVe to emulate an HDHomeRun tuner.","Configure xTeVe with your RegardezIPTV M3U and XMLTV URLs.","In Plex, navigate to Settings > Live TV & DVR and add the local xTeVe tuner."],"es":["Descargue Plex Media Server en su ordenador.","Instale un proxy IPTV como xTeVe para emular un sintonizador HDHomeRun.","Configure xTeVe con sus URL M3U y XMLTV de RegardezIPTV.","En Plex, vaya a Ajustes > Live TV y DVR y añada el sintonizador local xTeVe."],"de":["Laden Sie Plex Media Server auf Ihren PC herunter.","Installieren Sie einen IPTV-Proxy wie xTeVe, um einen HDHomeRun-Tuner zu simulieren.","Konfigurieren Sie xTeVe mit Ihrer RegardezIPTV M3U- und XMLTV-URL.","Gehen Sie in Plex auf Einstellungen > Live TV & DVR und fügen Sie den lokalen xTeVe-Tuner hinzu."]}',
 'active',24),

('TiviMate (Companion)','📺','box',0,
 '{"fr":"Premium à 4,99€/an","en":"Premium at €4.99/year","es":"Premium a 4,99€/año","de":"Premium für 4,99€/Jahr"}',
 '["Android TV","Fire Stick","Nvidia Shield"]','["tv","box"]',NULL,
 '{"fr":"Extension payante de TiviMate pour débloquer les fonctions avancées : multi-playlists, enregistrement et replay.","en":"TiviMate paid companion unlocking advanced features: multi-playlists, recording and catch-up TV.","es":"Complemento de pago de TiviMate para desbloquear funciones avanzadas: multi-listas, grabación y replay.","de":"Kostenpflichtige TiviMate-Erweiterung für erweiterte Funktionen: Multi-Playlists, Aufnahme und Replay."}',
 '{"fr":["Téléchargez TiviMate Companion depuis le Play Store.","Ouvrez l\'application et liez-la à votre compte TiviMate.","Activez votre abonnement Premium via l\'interface.","Retournez dans TiviMate principal pour débloquer toutes les fonctionnalités."],"en":["Download TiviMate Companion from the Play Store.","Open the app and link it to your TiviMate account.","Activate your Premium subscription through the interface.","Return to the main TiviMate app to unlock all features."],"es":["Descargue TiviMate Companion desde Play Store.","Abra la aplicación y vincúlela a su cuenta de TiviMate.","Active su suscripción Premium a través de la interfaz.","Regrese a la aplicación principal de TiviMate para desbloquear todas las funciones."],"de":["Laden Sie TiviMate Companion aus dem Play Store herunter.","Öffnen Sie die App und verknüpfen Sie sie mit Ihrem TiviMate-Konto.","Aktivieren Sie Ihr Premium-Abonnement über die Benutzeroberfläche.","Kehren Sie zur Haupt-TiviMate-App zurück, um alle Funktionen freizuschalten."]}',
 'active',25);
